# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 313c9a0843f61ac3c8d6cd046cc7932931494268b2e7f674ceae410618e0d62adc929873becb95a464ae09748ea904ba32262ce08b1cb632bb5a01f8742840f7

test:
  secret_key_base: c120a8cbba1a1f15327cf718794372308f249e4a53ff7b6d42aad8d7e1be16365c50af21a6c6783e25e3b3dee4d2bcf345fb998e2b2dba534830de7c7f8ca9ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
